export const CLASSES = ["1","2","3","4","5","6","7","8","9","10","11","12"];

export const SUBJECTS_BY_CLASS = {
  "1": ["English","Hindi","Mathematics","EVS"],
  "2": ["English","Hindi","Mathematics","EVS"],
  "3": ["English","Hindi","Mathematics","EVS"],
  "4": ["English","Hindi","Mathematics","EVS"],
  "5": ["English","Hindi","Mathematics","EVS"],
  "6": ["English","Hindi","Mathematics","Science","Social Science","Sanskrit"],
  "7": ["English","Hindi","Mathematics","Science","Social Science","Sanskrit"],
  "8": ["English","Hindi","Mathematics","Science","Social Science","Sanskrit"],
  "9": ["English","Hindi","Mathematics","Science","Social Science"],
  "10": ["English","Hindi","Mathematics","Science","Social Science"],
  "11": ["English","Physics","Chemistry","Mathematics","Biology","Economics","Accountancy","Business Studies","History","Geography","Political Science"],
  "12": ["English","Physics","Chemistry","Mathematics","Biology","Economics","Accountancy","Business Studies","History","Geography","Political Science"],
};

export const MEDIUMS = ["English","Hindi"];

export const CONDITIONS = [
  { id: "dyslexia", label: "Dyslexia", color: "bg-purple-100 text-purple-700", desc: "Reading & writing difficulties" },
  { id: "dyscalculia", label: "Dyscalculia", color: "bg-blue-100 text-blue-700", desc: "Number & math difficulties" },
  { id: "adhd", label: "ADHD", color: "bg-orange-100 text-orange-700", desc: "Attention & hyperactivity" },
  { id: "autism", label: "Autism Spectrum", color: "bg-rose-100 text-rose-700", desc: "Social & communication" },
  { id: "dysgraphia", label: "Dysgraphia", color: "bg-yellow-100 text-yellow-700", desc: "Writing & motor difficulties" },
  { id: "slow_learner", label: "Slow Learner", color: "bg-teal-100 text-teal-700", desc: "Needs more time & repetition" },
  { id: "gifted", label: "Gifted / High IQ", color: "bg-green-100 text-green-700", desc: "Advanced learner needs" },
  { id: "general", label: "General Support", color: "bg-gray-100 text-gray-700", desc: "Universal accommodations" },
];

export const IQ_RANGES = [
  { id: "below_70", label: "Below 70 (Intellectual Disability)" },
  { id: "70_84", label: "70–84 (Borderline)" },
  { id: "85_99", label: "85–99 (Low Average)" },
  { id: "100_114", label: "100–114 (Average to High Average)" },
  { id: "115_129", label: "115–129 (Above Average)" },
  { id: "130_plus", label: "130+ (Gifted)" },
  { id: "unknown", label: "Not Assessed / Unknown" },
];

export const RESOURCE_TYPES = ["Video","Article","Worksheet","Interactive","App","Audio","Book","Tool"];

// ─── Resource Database ───────────────────────────────────────────────
export const resources = [
  // ── MATHEMATICS ──────────────────────────────────────────────────
  {
    id: "m001",
    title: "Khan Academy – CBSE Maths (All Classes)",
    description: "Step-by-step video lessons aligned to CBSE curriculum covering all topics from Class 1–12. Ideal for dyscalculia: uses visual models, slow pace, and practice exercises with instant feedback.",
    url: "https://www.khanacademy.org/math",
    classes: ["1","2","3","4","5","6","7","8","9","10","11","12"],
    subject: "Mathematics",
    chapter: "All Chapters",
    medium: ["English"],
    conditions: ["dyscalculia","general","slow_learner","adhd"],
    type: "Video",
    source: "Khan Academy",
    free: true,
    rating: 5,
  },
  {
    id: "m002",
    title: "Maths Is Fun – Visual Explanations",
    description: "Clean, simple explanations with colorful diagrams for arithmetic, algebra, and geometry. Very low text density – ideal for dyslexia and slow learners.",
    url: "https://www.mathsisfun.com",
    classes: ["3","4","5","6","7","8","9","10"],
    subject: "Mathematics",
    chapter: "All Chapters",
    medium: ["English"],
    conditions: ["dyscalculia","dyslexia","slow_learner","general"],
    type: "Interactive",
    source: "Maths Is Fun",
    free: true,
    rating: 4,
  },
  {
    id: "m003",
    title: "Vedantu – CBSE Class 6 Fractions Video Lessons",
    description: "Hindi & English medium video lessons on fractions using animated visuals. Breaks concepts into very small steps – excellent for dyscalculia.",
    url: "https://www.vedantu.com/maths/fractions",
    classes: ["6"],
    subject: "Mathematics",
    chapter: "Fractions",
    medium: ["English","Hindi"],
    conditions: ["dyscalculia","slow_learner","general"],
    type: "Video",
    source: "Vedantu",
    free: true,
    rating: 4,
  },
  {
    id: "m004",
    title: "Dyscalculia.org – Number Sense Worksheets",
    description: "Printable worksheets specifically designed for children with dyscalculia. Uses manipulative-based approaches, dot patterns, and visual grouping.",
    url: "https://www.dyscalculia.org/math-tools",
    classes: ["1","2","3","4","5"],
    subject: "Mathematics",
    chapter: "Numbers",
    medium: ["English"],
    conditions: ["dyscalculia"],
    type: "Worksheet",
    source: "Dyscalculia.org",
    free: true,
    rating: 5,
  },
  {
    id: "m005",
    title: "BYJU'S – CBSE Class 9 & 10 Algebra",
    description: "Interactive algebra lessons with animations, concept videos, and practice problems. Adaptive difficulty adjusts to child's pace.",
    url: "https://byjus.com/maths/",
    classes: ["9","10"],
    subject: "Mathematics",
    chapter: "Algebra",
    medium: ["English","Hindi"],
    conditions: ["general","slow_learner","adhd"],
    type: "Interactive",
    source: "BYJU'S",
    free: false,
    rating: 4,
  },
  {
    id: "m006",
    title: "NCERT Exemplar – Maths Practice Problems",
    description: "Official NCERT problem sets with detailed solutions. Higher-order thinking problems suitable for gifted learners.",
    url: "https://ncert.nic.in/exemplar-problems.php",
    classes: ["6","7","8","9","10","11","12"],
    subject: "Mathematics",
    chapter: "All Chapters",
    medium: ["English","Hindi"],
    conditions: ["gifted","general"],
    type: "Book",
    source: "NCERT",
    free: true,
    rating: 5,
  },
  {
    id: "m007",
    title: "Prodigy – Gamified Math Practice",
    description: "A game-based math platform that adapts to the student's level. Excellent for ADHD and slow learners due to engagement through game mechanics.",
    url: "https://www.prodigygame.com",
    classes: ["1","2","3","4","5","6","7","8"],
    subject: "Mathematics",
    chapter: "All Chapters",
    medium: ["English"],
    conditions: ["adhd","slow_learner","dyscalculia","general"],
    type: "App",
    source: "Prodigy",
    free: true,
    rating: 5,
  },

  // ── ENGLISH ──────────────────────────────────────────────────────
  {
    id: "e001",
    title: "Starfall – Phonics & Reading for Dyslexia",
    description: "Structured phonics program using multisensory approach (visual, auditory, kinesthetic). Research-backed for dyslexia. Teaches letter-sound relationships systematically.",
    url: "https://www.starfall.com",
    classes: ["1","2","3","4","5"],
    subject: "English",
    chapter: "Reading & Phonics",
    medium: ["English"],
    conditions: ["dyslexia","slow_learner","general"],
    type: "Interactive",
    source: "Starfall",
    free: true,
    rating: 5,
  },
  {
    id: "e002",
    title: "Nessy – Reading & Spelling for Dyslexia",
    description: "Dyslexia-specific reading and spelling program with games, videos, and structured literacy approach. Used in schools worldwide.",
    url: "https://www.nessy.com",
    classes: ["1","2","3","4","5","6"],
    subject: "English",
    chapter: "Reading & Writing",
    medium: ["English"],
    conditions: ["dyslexia","dysgraphia"],
    type: "App",
    source: "Nessy",
    free: false,
    rating: 5,
  },
  {
    id: "e003",
    title: "Read Naturally – Fluency Building",
    description: "Audio-supported reading passages that build fluency and comprehension. Child reads along with audio, then independently. Great for dyslexia.",
    url: "https://www.readnaturally.com",
    classes: ["3","4","5","6","7","8"],
    subject: "English",
    chapter: "Reading Comprehension",
    medium: ["English"],
    conditions: ["dyslexia","slow_learner"],
    type: "Audio",
    source: "Read Naturally",
    free: false,
    rating: 4,
  },
  {
    id: "e004",
    title: "Understood.org – Dyslexia Learning Strategies",
    description: "Expert articles, videos, and strategies for parents and teachers on supporting children with dyslexia in reading and writing across all grade levels.",
    url: "https://www.understood.org/articles/dyslexia",
    classes: ["1","2","3","4","5","6","7","8","9","10"],
    subject: "English",
    chapter: "All Chapters",
    medium: ["English"],
    conditions: ["dyslexia","general"],
    type: "Article",
    source: "Understood.org",
    free: true,
    rating: 5,
  },
  {
    id: "e005",
    title: "British Council – LearnEnglish Kids",
    description: "Games, songs, stories, and activities to build English skills. Very visual and audio-based – suitable for dyslexia and autism spectrum learners.",
    url: "https://learnenglishkids.britishcouncil.org",
    classes: ["1","2","3","4","5","6"],
    subject: "English",
    chapter: "Grammar & Vocabulary",
    medium: ["English"],
    conditions: ["dyslexia","autism","adhd","general"],
    type: "Interactive",
    source: "British Council",
    free: true,
    rating: 4,
  },
  {
    id: "e006",
    title: "OpenDyslexic Font – Accessible Text Tool",
    description: "A free font designed for dyslexic readers with weighted bottoms to prevent letter flipping. Install on browsers to transform any website's text.",
    url: "https://opendyslexic.org",
    classes: ["1","2","3","4","5","6","7","8","9","10","11","12"],
    subject: "English",
    chapter: "All Chapters",
    medium: ["English"],
    conditions: ["dyslexia"],
    type: "Tool",
    source: "OpenDyslexic",
    free: true,
    rating: 5,
  },

  // ── SCIENCE ──────────────────────────────────────────────────────
  {
    id: "s001",
    title: "NCERT Science Textbooks (Free PDF)",
    description: "Official NCERT science textbooks for Classes 6–10 in English and Hindi. Available as free PDFs. Use with text-to-speech tools for dyslexia support.",
    url: "https://ncert.nic.in/textbook.php",
    classes: ["6","7","8","9","10"],
    subject: "Science",
    chapter: "All Chapters",
    medium: ["English","Hindi"],
    conditions: ["general","gifted"],
    type: "Book",
    source: "NCERT",
    free: true,
    rating: 5,
  },
  {
    id: "s002",
    title: "CK-12 – Adaptive Science Textbooks",
    description: "Free, interactive science textbooks that adapt to reading level. Includes videos, simulations, and simplified text versions. Excellent for slow learners and dyslexia.",
    url: "https://www.ck12.org",
    classes: ["6","7","8","9","10","11","12"],
    subject: "Science",
    chapter: "All Chapters",
    medium: ["English"],
    conditions: ["dyslexia","slow_learner","adhd","general"],
    type: "Interactive",
    source: "CK-12",
    free: true,
    rating: 5,
  },
  {
    id: "s003",
    title: "Amoeba Sisters – Biology Concept Videos",
    description: "Highly visual, animated biology videos with humor and clear language. Short (10–15 min). Great for ADHD, autism spectrum, and visual learners.",
    url: "https://www.youtube.com/@AmoebaSisters",
    classes: ["9","10","11","12"],
    subject: "Science",
    chapter: "Biology",
    medium: ["English"],
    conditions: ["adhd","autism","dyslexia","general"],
    type: "Video",
    source: "YouTube / Amoeba Sisters",
    free: true,
    rating: 5,
  },
  {
    id: "s004",
    title: "PhET Interactive Simulations – Physics & Chemistry",
    description: "University of Colorado's free science simulations. Hands-on virtual experiments for physics and chemistry topics. Visual and interactive – ideal for ADHD and autism.",
    url: "https://phet.colorado.edu",
    classes: ["8","9","10","11","12"],
    subject: "Science",
    chapter: "Physics & Chemistry",
    medium: ["English","Hindi"],
    conditions: ["adhd","autism","gifted","general"],
    type: "Interactive",
    source: "PhET / University of Colorado",
    free: true,
    rating: 5,
  },
  {
    id: "s005",
    title: "Diksha – CBSE Science (Hindi Medium)",
    description: "India's national e-learning platform with CBSE-aligned science content in Hindi. Videos, QR-code linked content, and practice questions.",
    url: "https://diksha.gov.in",
    classes: ["6","7","8","9","10"],
    subject: "Science",
    chapter: "All Chapters",
    medium: ["Hindi","English"],
    conditions: ["slow_learner","general"],
    type: "Video",
    source: "DIKSHA (Govt of India)",
    free: true,
    rating: 4,
  },

  // ── SOCIAL SCIENCE ───────────────────────────────────────────────
  {
    id: "ss001",
    title: "Geography Map Skills – Animated Videos",
    description: "Short animated videos explaining map skills, continents, climate zones for CBSE Social Science. Visual learning – good for dyslexia and slow learners.",
    url: "https://www.youtube.com/playlist?list=PLillGF-RfqbbJnYMPly6Bq0JTer8FGkHu",
    classes: ["6","7","8","9","10"],
    subject: "Social Science",
    chapter: "Geography",
    medium: ["English"],
    conditions: ["dyslexia","slow_learner","adhd","general"],
    type: "Video",
    source: "YouTube",
    free: true,
    rating: 4,
  },
  {
    id: "ss002",
    title: "NCERT Social Science eBooks",
    description: "Official free eBooks for Social Science – History, Civics, Geography. Can be used with screen readers and text-to-speech for accessibility.",
    url: "https://ncert.nic.in/textbook.php",
    classes: ["6","7","8","9","10"],
    subject: "Social Science",
    chapter: "All Chapters",
    medium: ["English","Hindi"],
    conditions: ["general","gifted"],
    type: "Book",
    source: "NCERT",
    free: true,
    rating: 5,
  },

  // ── HINDI ─────────────────────────────────────────────────────────
  {
    id: "h001",
    title: "Bolobooks – Hindi Audio Books for Children",
    description: "Hindi audio books for children. Listen along to stories and NCERT passages. Ideal for dyslexia and slow learners who struggle with Hindi reading.",
    url: "https://www.bolobooks.com",
    classes: ["1","2","3","4","5","6","7","8"],
    subject: "Hindi",
    chapter: "Reading & Comprehension",
    medium: ["Hindi"],
    conditions: ["dyslexia","slow_learner","general"],
    type: "Audio",
    source: "BoloBooks",
    free: true,
    rating: 4,
  },
  {
    id: "h002",
    title: "e-Pathshala – Hindi NCERT Textbooks",
    description: "NCERT Hindi textbooks (Vasant, Durva, Rimjhim etc.) available as free audio and ebooks via the government's e-Pathshala portal.",
    url: "https://epathshala.nic.in",
    classes: ["1","2","3","4","5","6","7","8","9","10"],
    subject: "Hindi",
    chapter: "All Chapters",
    medium: ["Hindi"],
    conditions: ["dyslexia","slow_learner","general"],
    type: "Audio",
    source: "e-Pathshala (Govt of India)",
    free: true,
    rating: 5,
  },

  // ── EVS ───────────────────────────────────────────────────────────
  {
    id: "ev001",
    title: "Toonly – Environmental Science Animated Videos (Classes 1–5)",
    description: "Colorful animated videos explaining EVS concepts like plants, animals, water, family, and neighbourhood. Very accessible for all learners.",
    url: "https://www.youtube.com/results?search_query=CBSE+EVS+class+animated",
    classes: ["1","2","3","4","5"],
    subject: "EVS",
    chapter: "All Chapters",
    medium: ["English","Hindi"],
    conditions: ["autism","adhd","slow_learner","dyslexia","general"],
    type: "Video",
    source: "YouTube",
    free: true,
    rating: 4,
  },

  // ── ADHD-SPECIFIC TOOLS ───────────────────────────────────────────
  {
    id: "adhd001",
    title: "Focusmate – Virtual Co-working for Study Focus",
    description: "Pairs your child with a study buddy via webcam for timed 25–50 min sessions. Highly effective for ADHD to maintain focus during homework.",
    url: "https://www.focusmate.com",
    classes: ["6","7","8","9","10","11","12"],
    subject: "All Subjects",
    chapter: "Study Strategy",
    medium: ["English"],
    conditions: ["adhd"],
    type: "Tool",
    source: "Focusmate",
    free: true,
    rating: 4,
  },
  {
    id: "adhd002",
    title: "Forest App – Focus Timer for Students",
    description: "A gamified Pomodoro timer app. Students grow a virtual tree while studying – leaving the app kills the tree. Great motivation tool for ADHD.",
    url: "https://www.forestapp.cc",
    classes: ["4","5","6","7","8","9","10","11","12"],
    subject: "All Subjects",
    chapter: "Study Strategy",
    medium: ["English"],
    conditions: ["adhd"],
    type: "App",
    source: "Forest App",
    free: true,
    rating: 5,
  },

  // ── AUTISM ───────────────────────────────────────────────────────
  {
    id: "au001",
    title: "Autism Speaks – School Support Toolkit",
    description: "A toolkit for parents to support their child with autism in a mainstream school. Includes IEP templates, communication strategies, and accommodation guides.",
    url: "https://www.autismspeaks.org/tool-kit/school-community-tool-kit",
    classes: ["1","2","3","4","5","6","7","8","9","10"],
    subject: "All Subjects",
    chapter: "General Support",
    medium: ["English"],
    conditions: ["autism"],
    type: "Article",
    source: "Autism Speaks",
    free: true,
    rating: 5,
  },
  {
    id: "au002",
    title: "Boardmaker – Visual Schedules & Communication Boards",
    description: "Creates visual schedules, social stories, and communication boards. Critical for students with autism to manage school day structure and transitions.",
    url: "https://goboardmaker.com",
    classes: ["1","2","3","4","5","6"],
    subject: "All Subjects",
    chapter: "Communication & Routine",
    medium: ["English"],
    conditions: ["autism"],
    type: "Tool",
    source: "Boardmaker",
    free: false,
    rating: 5,
  },

  // ── GIFTED ───────────────────────────────────────────────────────
  {
    id: "g001",
    title: "Brilliant.org – Deep Math & Science Exploration",
    description: "Interactive problem sets for advanced learners. Covers olympiad-level mathematics, logic, computer science. Ideal for gifted students looking for challenge beyond CBSE curriculum.",
    url: "https://brilliant.org",
    classes: ["7","8","9","10","11","12"],
    subject: "Mathematics",
    chapter: "Advanced Topics",
    medium: ["English"],
    conditions: ["gifted"],
    type: "Interactive",
    source: "Brilliant.org",
    free: false,
    rating: 5,
  },
  {
    id: "g002",
    title: "Art of Problem Solving (AoPS)",
    description: "World-class math competition preparation. Textbooks, online classes, and community for mathematically gifted students.",
    url: "https://artofproblemsolving.com",
    classes: ["7","8","9","10","11","12"],
    subject: "Mathematics",
    chapter: "Advanced Mathematics",
    medium: ["English"],
    conditions: ["gifted"],
    type: "Book",
    source: "AoPS",
    free: false,
    rating: 5,
  },

  // ── GENERAL ACCESSIBILITY TOOLS ──────────────────────────────────
  {
    id: "acc001",
    title: "Immersive Reader (Microsoft) – Text Accessibility",
    description: "Free text-to-speech and reading support built into Microsoft Edge, Word, and Teams. Adjusts font, spacing, syllables – excellent for dyslexia and slow learners.",
    url: "https://www.onenote.com/learningtools",
    classes: ["1","2","3","4","5","6","7","8","9","10","11","12"],
    subject: "All Subjects",
    chapter: "Accessibility Tool",
    medium: ["English","Hindi"],
    conditions: ["dyslexia","slow_learner","general"],
    type: "Tool",
    source: "Microsoft",
    free: true,
    rating: 5,
  },
  {
    id: "acc002",
    title: "Google Read&Write – Chrome Extension",
    description: "Text-to-speech, word prediction, picture dictionary, and highlighting tools as a Chrome extension. Works on any website or PDF.",
    url: "https://www.texthelp.com/products/read-and-write-for-google-chrome/",
    classes: ["1","2","3","4","5","6","7","8","9","10","11","12"],
    subject: "All Subjects",
    chapter: "Accessibility Tool",
    medium: ["English"],
    conditions: ["dyslexia","dysgraphia","slow_learner"],
    type: "Tool",
    source: "Texthelp",
    free: true,
    rating: 5,
  },
  {
    id: "acc003",
    title: "Dictation.io – Free Voice-to-Text",
    description: "Speak and your words appear as text. Free, browser-based voice typing tool. Great for dysgraphia – allows children to express ideas without struggling with handwriting.",
    url: "https://dictation.io",
    classes: ["3","4","5","6","7","8","9","10","11","12"],
    subject: "All Subjects",
    chapter: "Writing Support",
    medium: ["English","Hindi"],
    conditions: ["dysgraphia","dyslexia"],
    type: "Tool",
    source: "Dictation.io",
    free: true,
    rating: 4,
  },
];

// ─── Filter helper ─────────────────────────────────────────────────
export function filterResources({ classFilter, subjectFilter, conditionFilter, mediumFilter, typeFilter, searchQuery }) {
  return resources.filter((r) => {
    if (classFilter && classFilter !== "All" && !r.classes.includes(classFilter)) return false;
    if (subjectFilter && subjectFilter !== "All Subjects" && r.subject !== subjectFilter && r.subject !== "All Subjects") return false;
    if (conditionFilter && conditionFilter !== "All" && !r.conditions.includes(conditionFilter)) return false;
    if (mediumFilter && mediumFilter !== "All" && !r.medium.includes(mediumFilter)) return false;
    if (typeFilter && typeFilter !== "All" && r.type !== typeFilter) return false;
    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      if (!r.title.toLowerCase().includes(q) && !r.description.toLowerCase().includes(q) && !r.subject.toLowerCase().includes(q)) return false;
    }
    return true;
  });
}
